
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMENTARIO CORCHETE_D CORCHETE_I DIVIDE FALSO FIN_SENTENCIA ID IGUAL IMPRIMIR MAS MENOS MIENTRAS MULTIPLICA NUMERO PARENTESIS_D PARENTESIS_I POR SI SINO TIPO_CADENA_TEXTO TIPO_DECIMAL TIPO_ENTERO VARIABLE VERDADEROexpression : term MAS term\n                    | term MENOS termexpression : termterm : factor MULTIPLICA factor\n                | factor DIVIDE factorterm : factorfactor : NUMERO'
    
_lr_action_items = {'NUMERO':([0,5,6,7,8,],[4,4,4,4,4,]),'$end':([1,2,3,4,9,10,11,12,],[0,-3,-6,-7,-1,-2,-4,-5,]),'MAS':([2,3,4,11,12,],[5,-6,-7,-4,-5,]),'MENOS':([2,3,4,11,12,],[6,-6,-7,-4,-5,]),'MULTIPLICA':([3,4,],[7,-7,]),'DIVIDE':([3,4,],[8,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'term':([0,5,6,],[2,9,10,]),'factor':([0,5,6,7,8,],[3,3,3,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term MAS term','expression',3,'p_expression_plus','Parser.py',15),
  ('expression -> term MENOS term','expression',3,'p_expression_plus','Parser.py',16),
  ('expression -> term','expression',1,'p_expression_term','Parser.py',23),
  ('term -> factor MULTIPLICA factor','term',3,'p_term_times','Parser.py',27),
  ('term -> factor DIVIDE factor','term',3,'p_term_times','Parser.py',28),
  ('term -> factor','term',1,'p_term_factor','Parser.py',35),
  ('factor -> NUMERO','factor',1,'p_factor_number','Parser.py',39),
]
